### PR TITLE
Master dev lammps

### PR DESCRIPTION
**Pull request by cjknight**
Recreating pull request to track progress on coupling with LAMMPS.

### CODE REVIEW

**Comment by chemphys** [comment]
Hey @cjknight , this is the PR that adds the LAMMPS interface and the parallel implementation with MPI?

**Comment by cjknight** [comment]
Yup, this PR has everything to-date for running with LAMMPS.

**Comment by chemphys** [comment]
Hey @cjknight ,

I was trying to fix the conflicts by doing what git suggested:
```
git checkout -b cjknight-master-dev-lammps master-dev_lammps
git pull https://github.com/cjknight/MBX.git master-dev-lammps
``` 
An then fix them. After pulling your branch, and trying to compile the code, I have an issue with the `islocal` variable:
```
[ 76%] Building CXX object tests/unittests_v0.2.1a/CMakeFiles/unittest-systools.dir/unittest-systools.o
/home/mrierari/codes/MBX/src/tests/unittests_v0.2.1a/unittest-systools.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
/home/mrierari/codes/MBX/src/tests/unittests_v0.2.1a/unittest-systools.cpp:71:61: error: ‘islocal’ was not declared in this scope
         mon_type_count = systools::OrderMonomers(mon_names, islocal, sites_out, nat_out, original2current, orginal_order,
                                                             ^
/home/mrierari/codes/MBX/src/tests/unittests_v0.2.1a/unittest-systools.cpp:149:67: error: ‘islocal’ was not declared in this scope
          mon_type_count2 = systools::OrderMonomers(monomer_names, islocal, sites2, nat_out, original2current2,
                                                                   ^
/home/mrierari/codes/MBX/src/tests/unittests_v0.2.1a/unittest-systools.cpp:158:67: error: ‘islocal’ was not declared in this scope
          mon_type_count2 = systools::OrderMonomers(monomer_names, islocal, sites_out, nats2, original2current2,
                                                                   ^
make[5]: *** [tests/unittests_v0.2.1a/CMakeFiles/unittest-systools.dir/unittest-systools.o] Error 1
make[4]: *** [tests/unittests_v0.2.1a/CMakeFiles/unittest-systools.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [MBX-core-prefix/src/MBX-core-stamp/MBX-core-build] Error 2
make[1]: *** [CMakeFiles/MBX-core.dir/all] Error 2
make: *** [all] Error 
```

Is it possible that the header file was not added to stage?

Let me know, otherwise I will try to figure out what is happening!

**Comment by cjknight** [comment]
I thought I had the Travis builds passing with the latest commit for these unittests. The “setup_h2o_5_br_1.h" header should have islocal declared and initialized; I see it included in the PR.

**Comment by chemphys** [comment]
That is weird.
There has to be some divergence between my branch and your PR. Can you do a pull from master-dev_lammps to your branch to update it? Maybe copy the branch in case it gets messed up. If it does, I wil go ahead and fix things anually the best I can.


.   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
Marc Riera-Riambau
Graduate Student @ Paesani Group
University of California, San Diego
Phone: +1 858 750 9866
Mail: mrierari@ucsd.edu
________________________________

**Comment by chemphys** [comment]
OOOOOHH! I think is because the systools test now uses the water only system (to make it deployable without having to remove it)
I made a few changes in the unittests to allow myself to just add the tests containing systems we actually want to release. Could it be it?


.   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
Marc Riera-Riambau
Graduate Student @ Paesani Group
University of California, San Diego
Phone: +1 858 750 9866
Mail: mrierari@ucsd.edu
________________________________

**Comment by chemphys** [comment]
What I don't get is why it was not tracked to your branch.

**Comment by cjknight** [comment]
Just pulled from your master-dev_lammps. Resolving conflicts now.

**Comment by chemphys** [comment]
Cool, seems like it is ok!! I will have a look and merge it! Thanks Chris!

**Pull request merged**
