### PR TITLE
Master dev lammps

### PR DESCRIPTION
**Pull request by cjknight**
*) Support for non-orthogonal lattices enabled; tested with ice Ih config.
*) Modified AddMonomer to accept an integer 'tag' argument to uniquely identify particles for use in electrostatics nearest neighbor (NN) communication. MARC: this look OK?
*) Additional clean-up and removing of unused code.
*) Next commits looking at performance...

### CODE REVIEW

**Comment by chemphys** [comment]
Hey @cjknight , I will have a look and let you know by tomorrow. If it is OK, is it OK to merge?

**Comment by cjknight** [comment]
Yes, it can be merged if ‘tag’ changes look OK. I have performance optimizations coming next and I want to keep those separate since they’ll need more testing/discussion before acceptance.

**Comment by chemphys** [comment]
Hey @cjknight , can you run clang-format on the conflicting files? I think that will fix the problems. The MBX repo has already a .clangformat file in the home directory.

**Comment by cjknight** [comment]
Hmm.. seemed to have choked on several things I removed. Let me test and format before accepting this one.

**Review by chemphys — APPROVED** [review]

**Comment by chemphys** [comment]
Hey @cjknight , it looks great to me! The tag you added seems fine in terms of general structure. I will merge the PR so I update the repo.

Thanks!

**Comment by chemphys** [comment]
Let me knwo when is ready for merging. I am gonna wait for your OK

**Comment by cjknight** [comment]
My unittests pass. This is good to go.

**Comment by chemphys** [comment]
Great!! Thanks Chris!

**Pull request merged**
