### PR TITLE
some LAMMPS work and cleanup

### PR DESCRIPTION
**Pull request by cjknight**
Removed restriction that box origin needed to be at {0,0,0}. Some consolidation of logic to add molecules to MBX. Marked blocks of code to be removed in future PRs.

### CODE REVIEW

**Comment by chemphys** [comment]
@cjknight , let me know when this is ok to you and will review and merge!

**Comment by cjknight** [comment]
This one is good. I’m halfway through a commit for Get/Set FFT dimensions. That could be included here or kept separate as another PR.

**Comment by chemphys** [comment]
Lets just include it here. There is no rush on merging.

Thanks Chris!

Marc Riera Riambau
Paesani Lab
UC San Diego

________________________________

**Comment by cjknight** [comment]
Here's first pass on Get/Set FFT grid dimensions using json file. Still testing. 

I don't think it hurts to start review. No sanity checks yet for fft grids. Dipole solver should fail to converge on first step if grid is not appropriate.

**Review by chemphys — APPROVED** [review]

**Comment by chemphys** [comment]
Everything looks good to me so far.

**Comment by chemphys** [comment]
hey @cjknight , I did a merge from my unittests branch, and run clang format to some files in electrostatics. If there are conflicts is gonna be most likely because of that. I would recommend to run clang format and pull from master-dev.

See you!

**Comment by cjknight** [comment]
doing a lot of housekeeping on LAMMPS side. wait before merging this one

**Comment by cjknight** [comment]
should be good to go now.

**Review by chemphys — APPROVED** [review]

**Pull request merged**
